/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(mainPage)'}/detallesPartido` | `/detallesPartido`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(mainPage)'}/equipo` | `/equipo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(mainPage)'}/equipos` | `/equipos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(mainPage)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(mainPage)'}/ligas` | `/ligas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(mainPage)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/createAccount` | `/createAccount`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(mainPage)'}/detallesPartido` | `/detallesPartido`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(mainPage)'}/equipo` | `/equipo`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(mainPage)'}/equipos` | `/equipos`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(mainPage)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(mainPage)'}/ligas` | `/ligas`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(mainPage)'}/perfil` | `/perfil`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/createAccount` | `/createAccount`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(mainPage)'}/detallesPartido${`?${string}` | `#${string}` | ''}` | `/detallesPartido${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(mainPage)'}/equipo${`?${string}` | `#${string}` | ''}` | `/equipo${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(mainPage)'}/equipos${`?${string}` | `#${string}` | ''}` | `/equipos${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(mainPage)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(mainPage)'}/ligas${`?${string}` | `#${string}` | ''}` | `/ligas${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(mainPage)'}/perfil${`?${string}` | `#${string}` | ''}` | `/perfil${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/createAccount${`?${string}` | `#${string}` | ''}` | `/createAccount${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(mainPage)'}/detallesPartido` | `/detallesPartido`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(mainPage)'}/equipo` | `/equipo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(mainPage)'}/equipos` | `/equipos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(mainPage)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(mainPage)'}/ligas` | `/ligas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(mainPage)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/createAccount` | `/createAccount`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; };
    }
  }
}
